logLevel: INFO
messages:
    timeZoneCurrent: '-> Time zone for {1} is {2} ({3})' # 1 = Player, 2 = Time Zone ID, 3 = Time Zone Display Name
    timeZoneNotFound: '-> No time zone matches filter: {1}' # 1 = <TimeZone>
    timeZoneResult:
        line: '-> {1} ({2})' # 1 = Time Zone ID, 2 = Time Zone Display Name
        footer: '-> Page {1} of {2} ({3} time zones found)' # 1 = Current Page, 2 = Total Page Count, 3 = Total Time Zones
    timeZoneSuccess: '-> Set time zone for {1} to {2} ({3})' # 1 = Player, 2 = Time Zone, 3 = Time Zone Display Name
    requiresPlayer: '-> §cOnly in-game players§r can use the {1} command' # 1 = Command Label
    requiresArgument: '-> Required §cargument missing§r: {1}' # 1 = Argument Name
    unknownArgument: '-> §cUnable to determine§r §o{1}§r: {2}' # 1 = Argument Name, 2 = Argument Value
    reload: '-> {1} plugin §2reloaded' # 1 = Plugin Name
version: @VERSION@